### ISSUE TITLE
Failed to load the Remote-SSH package

### ISSUE THREAD

**Issue by andreknieriem** [dsone/remote-ssh#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.0 x64
**Electron**: 1.6.9
**OS**: DESKTOP-SPM4G7I
**Thrown From**: [Remote-SSH](https://github.com/dsone/remote-ssh) package 0.8.0

### Stack Trace

Failed to load the Remote-SSH package

```
At packageConfig is not defined

ReferenceError: packageConfig is not defined
    at /packages/remote-ssh/lib/remote-ssh.js:11:10)
    at /packages/remote-ssh/lib/remote-ssh.js:150:25)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.20.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.20.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (C:/Users/Andre%20Rinas/AppData/Local/atom/app-1.20.0/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.20.0/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.20.0/resources/app/src/package.js:887:35)
    at ~/AppData/Local/atom/app-1.20.0/resources/app/src/package.js:158:34
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.20.0/resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (~/AppData/Local/atom/app-1.20.0/resources/app/src/package.js:144:18)
    at PackageManager.module.exports.PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.20.0/resources/app/src/package-manager.js:565:22)
    at ~/AppData/Local/atom/app-1.20.0/resources/app/src/package-manager.js:479:25
    at Config.module.exports.Config.transact (~/AppData/Local/atom/app-1.20.0/resources/app/src/config.js:321:22)
    at PackageManager.module.exports.PackageManager.loadPackages (~/AppData/Local/atom/app-1.20.0/resources/app/src/package-manager.js:473:25)
    at ~/AppData/Local/atom/app-1.20.0/resources/app/src/atom-environment.js:810:34
```

### Commands

```
     -0:16.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
activate-power-mode 2.5.0 
atom-beautify 0.30.5 
atom-material-ui 2.0.4 
atom-pair 2.0.13 
autoclose-html 0.23.0 
busy-signal 1.4.3 
file-icons 2.1.11 
intentions 1.1.5 
language-blade 0.34.0 
linter 2.2.0 
linter-eslint 8.3.2 
linter-php 1.5.0 
linter-ui-default 1.6.10 
project-plus 1.0.0 
Remote-FTP 1.1.3 
Remote-SSH 0.8.0 
sourcefetch 0.0.0 
symbols-tree-view 0.14.0 
typo3 0.7.0 
```

**Comment by dsone** [comment]
Fixed in 0.8.1.
