### ISSUE TITLE
Failed to activate the remote-ssh package

### ISSUE THREAD

**Issue by mindcoordinate** [dsone/remote-ssh#11]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: macOS 11.2.1
**Thrown From**: [remote-ssh](https://github.com/dsone/remote-ssh) package 0.13.0

### Stack Trace

Failed to activate the remote-ssh package

```
At Cannot convert undefined or null to object

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.setupSettings (/packages/remote-ssh/lib/remote-ssh.js:83:10)
    at Object.activate (/packages/remote-ssh/lib/remote-ssh.js:31:8)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3531055)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3530467
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3528045)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3530327
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3530270)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:383646)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:383262
    at Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:332808)
    at PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:383212)
    at PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:382762)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:719168
    at async Promise.all (index 0)
    at AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:719653)
```

### Commands

```
```

### Non-Core Packages

```
aligner 1.2.4 
aligner-css 1.2.1 
aligner-javascript 1.3.0 
aligner-php 1.3.0 
atom-beautify 0.33.4 
atom-gooey-syntax 1.0.0 
atom-typescript 14.1.2 
auto-detect-indentation 1.3.0 
autoclose-tags 0.2.4 
chmod 0.1.1 
color-picker 2.3.0 
colorblind-syntax 2.0.0 
file-icons 2.1.46 
glowing-cursor 0.1.2 
idiomatic-dark-syntax 0.1.3 
last-cursor-position 1.1.0 
linter 3.3.0 
linter-jscs 4.2.4 
linter-php 1.6.1 
linter-ui-default 3.2.4 
minimap 4.39.8 
minimap-highlight-selected 4.6.5 
native-ui 0.27.0 
php-cs-fixer 4.2.0 
pigments 0.40.6 
project-manager 3.3.8 
pumpkin-syntax 1.0.0 
qolor 0.4.2 
remote-ftp 2.2.4 
remote-ssh 0.13.0 
selection-highlight 0.1.6 
slack-ui 0.8.0 
sort-lines 0.19.0 
sync-settings 5.2.6 
todo-show 2.3.2 
```

**Comment by dsone** [comment]
Changing name in 0.13 to adhere to npm default broke config reading.
That change is reverted in 0.13.2.
