### ISSUE TITLE
Uncaught TypeError: Data must be a string or a buffer

### ISSUE THREAD

**Issue by ccazzaniga** [dsone/remote-ssh#4]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.14.2
**Thrown From**: [Remote-SSH](https://github.com/dsone/remote-ssh) package 0.11.0

### Stack Trace

Uncaught TypeError: Data must be a string or a buffer

```
At crypto.js:99

TypeError: Data must be a string or a buffer
    at Hash.update (crypto.js:99:16)
    at Clipboard.md5 (/private/var/folders/_w/cms69h5j4hs0_xgtntd8zmmm0000gn/T/AppTranslocation/ACEEDCEF-05CC-42B2-BFF7-B8281DA864C8/d/Atom.app/Contents/Resources/app/static/<embedded>:1:678585)
    at Clipboard.write (/private/var/folders/_w/cms69h5j4hs0_xgtntd8zmmm0000gn/T/AppTranslocation/ACEEDCEF-05CC-42B2-BFF7-B8281DA864C8/d/Atom.app/Contents/Resources/app/static/<embedded>:1:678658)
    at /packages/Remote-SSH/lib/remote-ssh.js:275:23
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

### Commands

```
     -1:58 remote-ssh:create-config (div.panels-item)
     -1:47.8.0 core:backspace (input.hidden-input)
     -1:10.1.0 core:paste (input.hidden-input)
     -1:05.9.0 editor:newline (input.hidden-input)
     -0:48.6.0 remote-ssh:start (div.panels-item)
```

### Non-Core Packages

```
Remote-SSH 0.11.0 
```

**Comment by dsone** [comment]
Possibly related to #9 . Will be fixed in that context.
